local Icons = {
	Catalog = "rbxassetid://132847573851619",
	Avatar = "rbxassetid://81489458260315",
	Search = "rbxassetid://118685771787843",
	Filter = "rbxassetid://128741217923901",
	Clothing = "rbxassetid://15726694719",
	Accessories = "rbxassetid://14843436332",
	Body = "rbxassetid://140301041058153",
	Faces = "rbxassetid://138451313426532",
	Animation = "rbxassetid://1114393432",
	Bundles = "rbxassetid://78111289121317",
	Robux = "rbxassetid://11560341132",
	Reset = "rbxassetid://6723921202", -- TODO: Update with real icon asset ID
	Apply = "rbxassetid://11768914234", -- TODO: Update with real icon asset ID
	Save = "rbxassetid://11768914234", -- TODO: Update with real icon asset ID
}

return Icons
